/** Known MCP servers the generator can wire up. Add entries here to expand. */
interface McpServerDef {
  command: string;
  args: string[];
  env?: Record<string, string>;
  note: string;
}

const REGISTRY: Record<string, McpServerDef> = {
  context7: {
    command: "npx",
    args: ["-y", "@upstash/context7-mcp"],
    note: "Up-to-date, version-pinned library documentation.",
  },
};

export function knownMcp(id: string): boolean {
  return id in REGISTRY;
}

function serversFor(ids: string[]): Record<string, McpServerDef> {
  const out: Record<string, McpServerDef> = {};
  for (const id of ids) {
    if (REGISTRY[id]) out[id] = REGISTRY[id];
  }
  return out;
}

/** `.mcp.json` for Claude Code (key: `mcpServers`). */
export function buildClaudeMcp(ids: string[]): string {
  const servers = serversFor(ids);
  const mcpServers: Record<string, unknown> = {};
  for (const [id, def] of Object.entries(servers)) {
    mcpServers[id] = { command: def.command, args: def.args, ...(def.env ? { env: def.env } : {}) };
  }
  return JSON.stringify({ mcpServers }, null, 2);
}

/** `.vscode/mcp.json` for VS Code / Copilot (key: `servers`). */
export function buildVscodeMcp(ids: string[]): string {
  const servers = serversFor(ids);
  const out: Record<string, unknown> = {};
  for (const [id, def] of Object.entries(servers)) {
    out[id] = { command: def.command, args: def.args, ...(def.env ? { env: def.env } : {}) };
  }
  return JSON.stringify({ servers: out }, null, 2);
}

/**
 * `.opencode/opencode.json` for OpenCode (key: `mcp`). OpenCode reads `AGENTS.md` as its instructions and
 * discovers skills from `.claude/skills/` natively, so this dedicated, tool-owned file only declares MCP. It
 * deep-merges with the user's own OpenCode config (project + global), so it never clobbers their settings.
 * Only `$schema` + `mcp` are emitted (unknown top-level keys raise OpenCode's ConfigInvalidError).
 */
export function buildOpencodeMcp(ids: string[]): string {
  const servers = serversFor(ids);
  const mcp: Record<string, unknown> = {};
  for (const [id, def] of Object.entries(servers)) {
    mcp[id] = {
      type: "local",
      command: [def.command, ...def.args],
      enabled: true,
      ...(def.env ? { env: def.env } : {}),
    };
  }
  return JSON.stringify({ $schema: "https://opencode.ai/config.json", mcp }, null, 2);
}

/** TOML string literal (double-quoted, minimal escaping for our controlled values). */
function tomlStr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * `.codex/config.toml` for OpenAI Codex (project-scoped MCP). Codex reads `AGENTS.md` as its instructions, so
 * this file only declares `[mcp_servers.<id>]`. Deterministic (stable key order); empty set ⇒ header only.
 */
export function buildCodexMcp(ids: string[]): string {
  const servers = serversFor(ids);
  const lines = [
    "# Codex MCP servers — generated by ai-workspace. See https://developers.openai.com/codex/mcp",
  ];
  for (const [id, def] of Object.entries(servers)) {
    lines.push(
      "",
      `[mcp_servers.${id}]`,
      `command = ${tomlStr(def.command)}`,
      `args = [${def.args.map(tomlStr).join(", ")}]`,
    );
    if (def.env) {
      lines.push(`[mcp_servers.${id}.env]`);
      for (const [k, v] of Object.entries(def.env)) lines.push(`${k} = ${tomlStr(v)}`);
    }
  }
  return lines.join("\n") + "\n";
}
