/**
 * F6 — distribution packaging. Pure builders for the Claude Code **plugin** manifest and the private
 * **marketplace** catalog, plus an install guide. The `package` command projects the already-generated
 * `.claude/` artifacts into a distributable plugin (one umbrella plugin) served from this repo as a
 * private marketplace, and stages per-skill zips for upload to a claude.ai organization.
 *
 * Identity is the same composed source — this is another projection, never a second source of truth.
 */

import type { Config } from "../config/schema.js";
import { TEMPLATES_VERSION } from "../version.js";

function kebab(s: string): string {
  return s
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-")
    .toLowerCase();
}

const ORG_NAME: Record<string, string> = {
  example: "Example Co",
};

/**
 * Stable distribution identifiers. Defaults derive from `project.name`/`company`; `config.distribution`
 * overrides them so a canonical org plugin (e.g. `acme-ai-workspace`) can coexist with other org
 * plugins in one marketplace, independent of the consuming repo's name.
 */
export function names(config: Config): { slug: string; plugin: string; marketplace: string; owner: string } {
  const dist = config.distribution;
  const slug = kebab(config.project.name) || "workspace";
  const org = config.company.id;
  const owner = dist.owner ?? (org !== "none" ? (ORG_NAME[org] ?? org) : config.project.name);
  const plugin = kebab(dist.plugin ?? slug);
  const marketplace = kebab(dist.marketplace ?? (org !== "none" ? `${org}-tools` : `${slug}-tools`));
  return { slug, plugin, marketplace, owner };
}

/** `.claude-plugin/plugin.json` — the umbrella plugin manifest. */
export function pluginManifest(config: Config): Record<string, unknown> {
  const { plugin, owner } = names(config);
  return {
    name: plugin,
    description: `AI workspace for ${config.project.name} — Claude Code skills and commands (generated by ai-workspace).`,
    version: TEMPLATES_VERSION,
    author: { name: owner },
    license: "UNLICENSED",
  };
}

/** Root `.claude-plugin/marketplace.json` — this repo serves as a private marketplace. */
export function marketplaceManifest(config: Config): Record<string, unknown> {
  const { slug, plugin, marketplace, owner } = names(config);
  return {
    name: marketplace,
    owner: { name: owner },
    metadata: { pluginRoot: "./plugins" },
    plugins: [
      {
        name: plugin,
        source: slug,
        description: `AI workspace for ${config.project.name}.`,
        version: TEMPLATES_VERSION,
      },
    ],
  };
}

/** Per-repo plugin id (kebab): `<umbrella-plugin>-<repo>`. Used when `distribution.perRepo` is on. */
export function repoPluginName(config: Config, repoName: string): string {
  return kebab(`${names(config).plugin}-${repoName}`);
}

/** `<plugin>/.claude-plugin/plugin.json` for a per-repo plugin. */
export function repoPluginManifest(config: Config, repoName: string): Record<string, unknown> {
  const { owner } = names(config);
  return {
    name: repoPluginName(config, repoName),
    description: `AI workspace for ${config.project.name} · repo ${repoName} — Claude Code skills and commands (generated by ai-workspace).`,
    version: TEMPLATES_VERSION,
    author: { name: owner },
    license: "UNLICENSED",
  };
}

/** Marketplace catalog listing N plugins (one per repo) — the `distribution.perRepo` variant. */
export function marketplaceManifestMulti(
  config: Config,
  plugins: Array<{ name: string; source: string; description: string }>,
): Record<string, unknown> {
  const { marketplace, owner } = names(config);
  return {
    name: marketplace,
    owner: { name: owner },
    metadata: { pluginRoot: "./plugins" },
    plugins: plugins.map((p) => ({ ...p, version: TEMPLATES_VERSION })),
  };
}

/** Human install guide (project language not applied here — distribution doc kept in English for IT). */
export function installDoc(config: Config, repoRef: string, skillIds: string[]): string {
  const { plugin, marketplace } = names(config);
  const ref = repoRef || "<owner/repo or git URL of THIS repository>";
  const skillList = skillIds.map((s) => `  - \`${s}\``).join("\n");
  return `# Distribution & install — ${config.project.name}

This repository is a **private Claude Code marketplace**. The umbrella plugin \`${plugin}\` bundles the
generated skills and commands. Three install surfaces:

## 1. VS Code / CLI (Claude Code) — recommended for developers
The repo is the marketplace (\`.claude-plugin/marketplace.json\` + \`plugins/${plugin}/\`). In Claude Code:

\`\`\`
/plugin marketplace add ${ref}
/plugin install ${plugin}@${marketplace}
\`\`\`

Private repo: Claude Code uses your existing git credentials (e.g. \`gh auth login\`, SSH agent). For
background auto-updates, export a token (\`GITHUB_TOKEN\`/\`GH_TOKEN\`, or \`GITLAB_TOKEN\`) in your environment.
Update later with \`/plugin marketplace update ${marketplace}\`.

> Commit \`.claude-plugin/marketplace.json\` and \`plugins/${plugin}/\` so the marketplace serves the plugin.

## 2. Claude Desktop / Cowork (individual)
Use the plugin folder \`plugins/${plugin}/\` with \`claude --plugin-dir ./plugins/${plugin}\`, or host it as a
\`.zip\` and load with \`--plugin-url\`.

## 3. claude.ai Team/Enterprise — Desktop + Workspace for all users
Per-skill zips are staged in \`dist/org-skills/\`. An **organization Owner** uploads them in
**Organization settings → Skills → + Add** (each zip has \`SKILL.md\` at its root). Requires *Code execution
and file creation* and *Skills* enabled for the org. Skills are then provisioned to everyone (web, Desktop
chat, Cowork), on by default; members can toggle individually. Staged skills:

${skillList || "  (none)"}

---
Regenerate everything with \`ai-workspace package\`. Artifacts are deterministic (re-running is a no-op).
`;
}
