import { resolve } from "node:path";
import type { Config } from "../config/schema.js";
import { writeFile, writeIfMissing, type WriteResult } from "../render/writer.js";
import { phasesFor } from "./sdd.js";
import { docsPaths } from "./paths.js";
import { skillFrontmatter as frontmatter, aiwsId } from "./naming.js";
import type { Phase } from "../i18n/strings.js";

// AI skill → English only (token efficiency).
function sddSkill(p: Phase, config: Config): string {
  const store = docsPaths(config);
  const trigger = `Trigger: when planning/executing the ${p.name.replace("sdd-", "")} phase of a Spec-Driven Development change.`;
  const lines = [
    "## How to work",
    "- Read prior artifacts in the change folder before writing the next one.",
    config.sdd.backend === "none"
      ? "- Backend is `none`: artifacts are not persisted to disk."
      : `- Artifacts live in \`${store.changes}/<change>/\` and are versioned in git.`,
    "- Follow the SDD lifecycle and conventions in AGENTS.md and `_shared/sdd-convention.md`.",
  ];
  return [frontmatter(aiwsId(p.name), `${p.summary} ${trigger}`), `## ${aiwsId(p.name)}`, "", p.does, "", ...lines].join("\n");
}

// AI skill (shared convention) → English only (token efficiency).
function sddConvention(config: Config): string {
  const s = docsPaths(config);
  return `# SDD store convention (shared)

SDD artifacts are plain markdown, versioned in git, readable by any AI tool. Follows OpenSpec's
*layout* (specs + changes + archive) as a convention — no external CLI.

Layout:
- \`${s.specs}/\`            — stable specifications (the current truth)
- \`${s.changes}/<name>/\`   — an in-flight change
  - \`explore.md\`  · investigation and options
  - \`proposal.md\` · intent, scope, approach, risks
  - \`spec.md\`     · requirements + acceptance scenarios (WHAT)
  - \`design.md\`   · technical design + Mermaid diagrams (HOW)
  - \`tasks.md\`    · ordered checklist (progress)
  - \`verify-report.md\` · validation against the spec
- \`${s.archive}/\`  — completed changes

Rules:
- One change folder per logical change. Keep the spec as the source of truth for behavior.
- Archive a change only after verify passes; fold its delta into \`${s.specs}/\`.
`;
}

// AI skill → English only (token efficiency).
function livingDocsSkillBody(config: Config): string {
  const p = docsPaths(config);
  return `## aiws-living-docs

Maintain an always-current, token-cheap snapshot of the project so agents get context without
re-scanning the repo.

## What to keep current
- \`${p.status}/PROJECT-STATE.md\` — overview, module map, decisions log, current status.
- \`${p.status}/ARCHITECTURE.md\` — architecture with Mermaid diagrams.

## How to update
1. Scan recent changes (git status/log, modified modules).
2. If SDD is active, summarize each folder under \`${p.changes}/*\`.
3. Rewrite only content inside \`ai-workspace:begin/end\` markers; preserve manual notes outside.
4. Keep it concise and scannable — this is read often.

Invoke via the \`/doc-sync\` command (Claude) or the \`doc-sync\` prompt (Copilot).
`;
}

/** Generate vendored skills into the repo (`.claude/skills/`). Claude target only. */
export function generateSkills(cwd: string, config: Config): WriteResult[] {
  const results: WriteResult[] = [];
  if (!config.targets.includes("claude")) return results;

  if (config.sdd.enabled && config.sdd.vendorSkills) {
    for (const p of phasesFor(config)) {
      results.push(writeFile(resolve(cwd, `.claude/skills/${aiwsId(p.name)}/SKILL.md`), sddSkill(p, config)));
    }
    results.push(
      writeIfMissing(
        resolve(cwd, ".claude/skills/_shared/sdd-convention.md"),
        sddConvention(config),
      ),
    );
    // REASONS-mode skills (sdd-spec-schema/onboarding/migrate, builder, audits) live in skill-packs/
    // (skills-as-data) — generated by generateStackPacks via declarative gating + tokens.
  }

  // Company business-content skills (corp-*) are an optional extension: ship your own packs in skill-packs/.

  if (config.livingDocs) {
    const desc = "Keep the living docs (project status) current so the AI always has fresh project context. Trigger: after finishing a task or when project state changed.";
    results.push(
      writeFile(
        resolve(cwd, ".claude/skills/aiws-living-docs/SKILL.md"),
        frontmatter("aiws-living-docs", desc) + livingDocsSkillBody(config),
      ),
    );
  }

  return results;
}
